# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944a05a1230adbabc701e481e13c8f4b830e7eb9d0433358cefbb41c06e3194a45932bf8b2ec99f889e9580b4a589574bcf16d23b19a8582f18bf9e538a03483

test:
  secret_key_base: 0d40ad9d351454ae4f35e5d3a17631b255c532676b6129c351d1038efdba2ddd970a85407e82d245a48708a03005c5e365a6378b9fdbf0896f8b8c56d887ba02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
